# Generated by Django 5.0.1 on 2024-01-04 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_episods_film_video_filmview_serials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='video',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='episods',
            name='videofile',
        ),
        migrations.RemoveField(
            model_name='serials',
            name='videofile',
        ),
        migrations.AddField(
            model_name='episods',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%y', validators=[django.core.validators.FileExtensionValidator(['mp4'])]),
        ),
        migrations.AddField(
            model_name='serials',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
