# Generated by Django 5.0.1 on 2024-01-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_rename_video_film_source_remove_episods_videofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='name',
        ),
        migrations.AddField(
            model_name='filmview',
            name='name',
            field=models.CharField(default='.', max_length=200),
        ),
    ]
