# Generated by Django 5.0.1 on 2024-01-05 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_remove_film_name_filmview_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episods',
            name='length',
        ),
    ]
